<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>WinExe</OutputType><TargetFramework>net6.0-windows</TargetFramework><Nullable>enable</Nullable><UseWindowsForms>true</UseWindowsForms><ImplicitUsings>disable</ImplicitUsings></PropertyGroup><ItemGroup><Compile Update="UI\Form1.Designer.cs"><DependentUpon>Form1.cs</DependentUpon></Compile><EmbeddedResource Update="UI\Form1.resx"><DependentUpon>Form1.cs</DependentUpon></EmbeddedResource></ItemGroup></Project>
